version: '3.7'

services:
  apache:
    image: httpd:latest
    volumes:
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./htpasswd/.htpasswd:/tmp/htpasswd # Ensure this path matches the AuthUserFile directive in httpd.conf
    ports:
      - "80:80"
    depends_on:
      - grafana

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_AUTH_PROXY_ENABLED: 'true'
      GF_AUTH_PROXY_HEADER_NAME: 'X-WEBAUTH-USER'
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_USERS_AUTO_ASSIGN_ORG: 'true'
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: 'Editor'
    user: "472"
    ports:
      - "3000:3000"
